apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "service.fullname" . }}
  labels:
    {{- include "service.labels" . | nindent 4 }}
spec:
{{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
{{- end }}
  selector:
    matchLabels:
      {{- include "service.selectorLabels" . | nindent 6 }}
  template:
    metadata:
    {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        {{- include "service.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "service.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: http
            initialDelaySeconds: 300
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: http
            initialDelaySeconds: 300
            periodSeconds: 20
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
          - name: JAVA_OPTS
            valueFrom:
              configMapKeyRef:
                name: {{ include "service.fullname" . }}-configmap
                key: java-opts
          - name: server.use-forward-headers
            value: 'true'
          - name: spring.config.location
            value: 'file:/application.yml'
          - name: spring.data.mongodb.uri
            valueFrom:
              secretKeyRef:
                name: {{ include "service.fullname" . }}-secret
                key: mongodb-uri
          - name: jwt.token.secret
            valueFrom:
              secretKeyRef:
                name: {{ include "service.fullname" . }}-secret
                key: jwt.token.secret
            {{- if .Values.oauth2.client.provider.azure.enabled }}
          - name: spring.security.oauth2.client.registration.azure.clientSecret
            valueFrom:
              secretKeyRef:
                name: {{ include "service.fullname" . }}-secret
                key: oauth2.client.registration.azure.clientSecret
          - name: spring.security.oauth2.client.registration.azure.clientId
            valueFrom:
              secretKeyRef:
                name: {{ include "service.fullname" . }}-secret
                key: oauth2.client.registration.azure.clientId
            {{- end }}
            {{- if .Values.oauth2.client.provider.github.enabled }}
          - name: spring.security.oauth2.client.registration.github.clientSecret
            valueFrom:
              secretKeyRef:
                name: {{ include "service.fullname" . }}-secret
                key: oauth2.client.registration.github.clientSecret
          - name: spring.security.oauth2.client.registration.github.clientId
            valueFrom:
              secretKeyRef:
                name: {{ include "service.fullname" . }}-secret
                key: oauth2.client.registration.github.clientId
            {{- end }}
            {{- if .Values.oauth2.client.provider.google.enabled }}
          - name: spring.security.oauth2.client.registration.google.clientSecret
            valueFrom:
              secretKeyRef:
                name: {{ include "service.fullname" . }}-secret
                key: oauth2.client.registration.google.clientSecret
          - name: spring.security.oauth2.client.registration.google.clientId
            valueFrom:
              secretKeyRef:
                name: {{ include "service.fullname" . }}-secret
                key: oauth2.client.registration.google.clientId
            {{- end }}
          volumeMounts:
          - name: application-yaml
            mountPath: /application.yml
            readOnly: true            
            subPath: application.yml
      volumes:
      - name: application-yaml
        configMap:
          name: {{ include "service.fullname" . }}-configmap
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
