apiVersion: v1
kind: Secret
metadata:
  name: {{ include "service.fullname" . }}-secret 
data:
  jwt.token.secret: {{ .Values.jwt.token.secret | b64enc |  quote }}
  {{- with .Values.oauth2.client }}
  {{- if .provider.azure.enabled }}
  oauth2.client.registration.azure.clientSecret: {{ .registration.azure.clientSecret | b64enc |  quote }}
  oauth2.client.registration.azure.clientId: {{ .registration.azure.clientId | b64enc |  quote }}
  {{- end }}
  {{- if .provider.github.enabled }}
  oauth2.client.registration.github.clientSecret: {{ .registration.github.clientSecret | b64enc |  quote }}
  oauth2.client.registration.github.clientId: {{ .registration.github.clientId | b64enc |  quote }}
  {{- end }}
  {{- if .provider.google.enabled }}
  oauth2.client.registration.google.clientSecret: {{ .registration.google.clientSecret | b64enc |  quote }}
  oauth2.client.registration.google.clientId: {{ .registration.google.clientId | b64enc |  quote }}
  {{- end }}
  {{- end }}
  mongodb-uri: {{ with .Values.secret.mongodb_uri -}}  
  {{- list .dbprotocol "://" .username ":" .password "@" .dbhost_and_port "/" .dbconn | join ""  | b64enc |  quote }}
# {{- ( printf "%s%s:%s@%s-%s%s" "mongodb://" .username .password $.Release.Name "database" ":27017/guestbook?authSource=admin" ) | b64enc | quote }}
{{- end }}
