apiVersion: v2
name: xldeploy-argos-collector
description: A Helm chart for Kubernetes

type: application
version: 0.0.1
appVersion: 0.0.1-RC7
dependencies:
  - name: argos-collector
    version: 0.0.1
    repository: "@argosnotary"
