apiVersion: v2
name: argosnotary
version: 0.0.1
description: Argos Notary
home: https://argosnotary.github.io
keywords:
  - argos
  - notary
type: application
sources:
  - https://github.com/argosnotary
dependencies:
  - name: mongodb
    version: 7.14.0
    repository: https://charts.bitnami.com/bitnami
    condition: mongodb.enabled
  - name: oauthstub
    version: 0.0.1
    repository: "@argosnotary"
    condition: global.oauthstub.enabled
maintainers:
  - name: Gerard Borst
  - name: Michel Durieux
  - name: Bart Kors
appVersion: 0.0.1-RC7
