global:
  oauthstub:
    enabled: true
    ip: "172.17.0.3"

frontend:
#  autoscaling:
#    enabled: false   
  image:
    repository: argosnotary/argos-frontend
  ingress:
    enabled: true
    annotations: {}
    hosts:
      - host: argosnotary.local
    tls:
      - secretName: frontend-tls-local-secret
        hosts:
          - argos.local

service:
  secret:
    mongodb_uri:
      password: password
      dbhost_and_port: "<db host>"
  image:
    repository: argosnotary/argos-service

mongodb:
  enabled: true
  replicaSet:
    enabled: true
  mongodbRootPassword: password


  