global:
  oauthstub:
    enabled: true

frontend:
  ingress:
    enabled: true
    annotations: {}
    hosts:
      - host: argosnotary.local
    tls:
      - secretName: frontend-tls-local-secret
        hosts:
          - argosnotary.local

service:
  secret:
    mongodb_uri:
      password: password
      dbhost_and_port: "argos-mongodb"
  oauth2:
    client:
      provider:
        azure:
          enabled: true
          authorizationUri: http://oauthstub.local/oauth2/v2.0/authorize-manual
          tokenUri: http://argos-oauthstub:8080/oauth2/v2.0/token
          userInfoUri: http://argos-oauthstub:8080/v1.0/me
  auth:
    frontendRedirectBasePath: https://argosnotary.local
  jwt:
    token:
      secret: Z2LcVpgCuGtpb5rBDNIIWGe8RXqYGWDpWFjWhYQUS2Z8rjE2/GTJlu0s6BRYG0Mn0kV8StC9cFE83Jkl68RCkw==

mongodb:
  enabled: true
  replicaSet:
    enabled: true
  mongodbRootPassword: password


  