{{- if gt .Values.replicaCount 1.0 -}}
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: {{ include "argos-collector.fullname" . }}
spec:
  minAvailable: 1
  selector:
    matchLabels:
      {{- include "argos-collector.selectorLabels" . | nindent 10 }}
{{- end }}